### PR TITLE
Upgrading the kafka client library used by driver-kafka of SBK to ver…

### PR DESCRIPTION
**Pull request by Amartya-Mahato**
Upgrading the kafka client library used by driver-kafka of SBK to version 3.0+
`api "org.apache.kafka:kafka-clients:2.4.1"`
to
`api "org.apache.kafka:kafka-clients:3.1.0"`

### CODE REVIEW

**Comment by kmgowda** [comment]
@Amartya-Mahato  After upgrading to latest version of kafka client , the build is failing ; fix the compilation issues

**Comment by Amartya-Mahato** [comment]
@kmgowda hi, sir i think the error is in kafka.java 
it's not supporting the import ``import org.apache.kafka.common.requests.IsolationLevel;``
instead it's requesting me to import ``import org.apache.kafka.common.IsolationLevel;``

**Comment by Amartya-Mahato** [comment]
@kmgowda hi, sir i think the error is in kafka.java 
it's not supporting the import ``import org.apache.kafka.common.requests.IsolationLevel;``
instead it's requesting me to import ``import org.apache.kafka.common.IsolationLevel;``
Should i go with it?

**Comment by kmgowda** [comment]
> @kmgowda hi, sir i think the error is in kafka.java it's not supporting the import `import org.apache.kafka.common.requests.IsolationLevel;` instead it's requesting me to import `import org.apache.kafka.common.IsolationLevel;` Should i go with it?
> 
> Ok let me try without it!

yes , you can import org.apache.kafka.common.IsolationLevel  and submit again.. build should pass to accept this PR.

**Pull request closed without merging**
